### ISSUE TITLE
Can I Make it for Public usable .If so What are the permission should in need 

### ISSUE THREAD

**Issue by arvs47** [RitwikGA/FacebookPageFeedTracker#1]
Suppose I am going to launch this as a public app which uses my app than their app details 
What scopes should i Ask for the Review Process .
I Need public page Feed Access .
Manage_pages
and Publish_pages 
What else .
Webhook can be replaced with the public page access feed right .> if i want the user just need to enter their page url or public facebook page url to get their page feed on the sheet < what codes should i replace ( if you have the code You can sent Me ) i am not a Pro coder . So that modification might be helpful to archive what i wish > 
Thank You

**Comment by RitwikGA** [comment]
Yes. You can use those permissions.  

Most of the code will need to be modified if you want to replace webhooks. I haven't yet worked on that yet.
I would suggest starting out with graph API explorer: https://developers.facebook.com/tools/explorer/
& test the endpoint URLs for the data you need.

**Comment by arvs47** [comment]
Ok I have those code but it works without UI and and the feed getting back
are not sorted as it needs .. will share those codes once I implement them
but I need your help to do the exception handlings
